apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy-pod-label
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy-pod-label
  template:
    metadata:
      labels:
        app: reverseproxy-pod-label
    spec:
      containers:
      - image: nkalra0123/reverse-proxy
        name: reverseproxy-pod-name
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


