apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_USERNAME: 
  POSTGRES_PASSWORD: 
  POSTGRES_HOST: 
  POSTGRES_DB: 
  AWS_BUCKET: 
  AWS_REGION: 
  AWS_PROFILE:
  JWT_SECRET: 
  URL: 
