apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-frontend-pod-label
  name: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend-pod-label
  template:
    metadata:
      labels:
        app: udagram-frontend-pod-label
    spec:
      containers:
      - image: nkalra0123/udagram-frontend
        name: udagram-frontend-pod-name
        imagePullPolicy: Always          
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: secrets
      restartPolicy: Always


