apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed-svc
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8080
  selector:
    service: udagram-api-feed
