apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-users
  name: udagram-api-users-svc
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    app: udagram-api-users-pod-label
