apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udagram-api-feed-pod-label
  name: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed-pod-label
  template:
    metadata:
      labels:
        app: udagram-api-feed-pod-label
    spec:
      containers:
      - image: nkalra0123/udagram-api-feed
        name: udagram-api-feed-pod-name
        imagePullPolicy: Always          
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
        envFrom:
          - secretRef:
              name: secrets
      restartPolicy: Always


